routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\WelcomeController::class, 'index'])->name('welcome');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
Route::get('/admin', [App\Http\Controllers\AdminController::class, 'index'])->name('home');
Route::resource('service', '\App\Http\Controllers\ServiceController')->middleware('auth');

/* Inicia rutas para perfil de usuario */
Route::get('profile/create', [App\Http\Controllers\ProfileController::class, 'create'])->name('profile.create')->middleware('auth');
Route::post('profile', [App\Http\Controllers\ProfileController::class, 'store'])->name('profile.store')->middleware('auth');
Route::get('profile/edit', [App\Http\Controllers\ProfileController::class, 'edit'])->name('profile.edit')->middleware('auth');
Route::put('profile/update', [App\Http\Controllers\ProfileController::class, 'update'])->name('profile.update')->middleware('auth');
/* == Finaliza rutas para perfil de usuario == */

/* Inicia rutas para sistema de comunicacion en perfil servicio */
Route::post('post', [App\Http\Controllers\PostController::class, 'store'])->name('post.store')->middleware('auth');
Route::post('comment', [App\Http\Controllers\CommentController::class, 'store'])->name('comment.store')->middleware('auth');
/* Fin de rutas para comunicacion en perfil servicio */

Route::get('profile/{profile}', [App\Http\Controllers\ProfileController::class, 'show'])->name('profile.show')->middleware('auth');

/*Inicia rutas para calificacion de servicio */
Route::put('rating/{rating}', [App\Http\Controllers\RatingController::class, 'update'])->name('rating.update')->middleware('auth');
Route::get('service/{prom}', [App\Http\Controllers\RatingController::class, 'average'])->name('toServiceController');

/* Inicia ruta para eliminar usuario */
Route::delete('user/delete', [App\Http\Controllers\ProfileController::class, 'destroy'])->name('user.destroy')->middleware('auth');
/* == Finaliza ruta para eliminar usuario == */


/* Inicio ruta para manejar purchases */
Route::post('purchase/store', [App\Http\Controllers\PurchaseController::class, 'store'])->name('purchase.store')->middleware('auth');
Route::get('purchase/{purchase}/edit', [App\Http\Controllers\PurchaseController::class, 'edit'])->name('purchase.edit')->middleware('auth');
Route::get('purchase/{purchase}', [App\Http\Controllers\PurchaseController::class, 'show'])->name('purchase.show')->middleware('auth');
Route::put('purchase/{purchase}', [App\Http\Controllers\PurchaseController::class, 'update'])->name('purchase.update')->middleware('auth');
/* == Finaliza rutas para manejar purchases == */

/* Inicio ruta de proceso de pago */
Route::post('/paypal', [App\Http\Controllers\PaymentController::class, 'payWithpaypal'])->name('paypal')->middleware('auth');

/* Ruta de estado de pago */
Route::get('/status/{purchase}', [App\Http\Controllers\PaymentController::class, 'getPaymentStatus'])->name('status')->middleware('auth');


/* Ruta para preguntas frecuentes */
Route::get('/faqs', [App\Http\Controllers\FaqsController::class,'show'])->name('faqs.show')->middleware('auth');

/* Inicia rutas para manejar likes */
Route::post('like/store', [App\Http\Controllers\LikeController::class, 'store'])->name('like.store')->middleware('auth');
Route::delete('like/{like}/delete', [App\Http\Controllers\LikeController::class, 'destroy'])->name('like.destroy')->middleware('auth');
/* == Finaliza ruta para manejar likes == */
/* Ruta de estado de chat */
Route::get('/purchase/mensajeria/{code}/', [App\Http\Controllers\ChatController::class, 'index'])->name('chat');

/* Rutas solo admin */
Route::get('/users/all', [App\Http\Controllers\UserController::class, 'index'])->name('user.index');
Route::get('/users/{user}/menu', [App\Http\Controllers\UserController::class, 'menu'])->name('user.menu');
Route::delete('/users/{user}/delete', [App\Http\Controllers\UserController::class, 'remove'])->name('user.delete');
Route::put('/users/{user}/change', [App\Http\Controllers\UserController::class, 'change'])->name('user.change');
Route::get('/purchases/all', [App\Http\Controllers\PurchaseController::class, 'index'])->name('purchase.index')->middleware('auth')->middleware('onlyadmin');
Route::get('/services/getall', [App\Http\Controllers\ServiceController::class, 'getall'])->name('service.getall')->middleware('auth')->middleware('onlyadmin');
Route::get('/purchases/general', [App\Http\Controllers\PurchaseController::class, 'general'])->name('purchase.general')->middleware('auth')->middleware('onlyadmin');

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id','type_service_id','title', 'description', 'price', 'picture'
    ];

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function type_service()
    {
        return $this->belongsTo('App\Models\TypeService');
    }

    /**
     * Set the scope search
     */
    public function scopeSearch($query,$search){
        if($search){
            return $query->where  ('title','LIKE',"%$search%")
                ->orWhere('description','LIKE',"%$search%");
        }
    }

    /**
     * Get the posts for the service.
     */
    public function posts()
    {
        return $this->hasMany('App\Models\Post');
    }

    /**
     * Get the purchases for the service
     */
    public function purchases()
    {
        return $this->hasMany('App\Models\Purchase');
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Like;
use App\Models\Service;
use App\Models\Purchase;
use App\Models\Rating;
use App\Models\TypeService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('buscar');
        $type_services = TypeService::select('id','category')->get();
        $services = Service::where('user_id', \Auth::user()->id)->get();
        return view('services.index', [
            "services" => $services,
            "busqueda" => $search,
            'type_services' => $type_services
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function getall()
    {
        $services = Service::all();
        return view('services.getall', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $type_services = TypeService::select('id','category')->get();
        return view('services.create', [
            'type_services' => $type_services]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $fields = [
            'title'=> 'required|string|max:100',
            'description'=> 'string|max:1000',
            'price'=> 'required|regex:/^[0-9]+(\.[0-9]{1,3})?$/|max:7',
            'picture_path'=>'max:10000|mimes:jpeg,png,jpg'
        ];
        $message = ["required"=>' :attribute es requerido' ];
        $this->validate($request, $fields, $message);
        // $serviceData=request()->all();

        $serviceData = request()->except('_token');
        $serviceData['user_id'] = \Auth::user()->id;

        if($request->hasFile('picture_path')){
            $serviceData['picture_path'] = $request->file('picture_path')->store('uploads','public');
        }


        Service::insert( $serviceData);
        //return response()->json($daserviceData
        return redirect('service')->with('message','Servicio agregado con exito');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(Service $service)
    {
        $rating_available = False;
        $rating_id = null;
        $purchase = null;
        $purchases = Purchase::where('service_id', '=', $service->id)->get();
        foreach ($purchases as $loop_purchase) {
            if ($loop_purchase->status && !$loop_purchase->rating->comment) {
                $rating_available = True;
                $rating_id = $loop_purchase->rating->id;
            } elseif (!$loop_purchase->status) {
                $purchase = $loop_purchase;
            }
        }

        $rating = Rating::where('id', $rating_id)->first();

        //Calculo del promedio de ratings
        $prom = 0;
        $average_ratings = Purchase::join('ratings', 'rating_id', '=', 'ratings.id')
                    ->where('service_id', $service->id)
                    ->where('comment', '!=', 'null')
                    ->get();

        foreach ($average_ratings as $average_rating){
            $prom = $prom + ($average_rating->type_rating_id)/$average_ratings->count();
        }
        $prom = round($prom,1,PHP_ROUND_HALF_UP);
        //!-- Fin calculo
        $liked_id = array();
        $liked_posts = array();
        $like = null;

        foreach ($service->posts as $post) {
            $like = Like::where([
                ['user_id', \Auth::user()->id],
                ['post_id', $post->id],
            ])->first();
            if ($like) {
                array_push($liked_posts, $post->id);
                array_push($liked_id, $like->id);
            }
        }
        return view("services.show", [
            'service' => $service,
            'rating_available' => $rating_available,
            'rating' => $rating,
            'purchase' => $purchase,
            'prom' => $prom,
            'liked_posts' => $liked_posts,
            'liked_id' => $liked_id,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {

        $type_services = TypeService::select('id','category')->get();
        return view('services.edit', [
            'type_services' => $type_services,
            'service'=> $service]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Service $service)
    {
        $fields = [
            'title'=> 'required|string|max:100',
            'description'=> 'string|max:1000',
            'price'=> 'required|regex:/^[0-9]+(\.[0-9]{1,3})?$/|max:7',
            'picture_path'=>'max:10000|mimes:jpeg,png,jpg'
        ];

        if($request->hasFile('picture_path')){

            $fields += ['picture_path'=>'max:10000|mimes:jpeg,png,jpg'];

        }

        $message = ["required"=>' :attribute es requerido' ];

        $this->validate($request, $fields, $message);

        $dataService = request()->except(['_token','_method']);


        if($request->hasFile('picture_path')){
            Storage::delete('public/'.$service->picture_path);
            $dataService['picture_path'] = $request->file('picture_path')->store('uploads','public');
            $service->update($dataService);
            return redirect('service')->with('message', 'Informacion modificada con exito');
        }

        $service->update($dataService);

        return redirect('service')->with('message','Información modificada con exito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(Service $service)
    {
//        if(Storage::delete('public/'.$service->picture_path)){
//            $service->delete();
//        }
        $service->delete();
        return redirect('service')->with('message','Servicio eliminado');
    }
}

resources/views/services/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @if(count($errors)>0)
    <div class="alert alert-danger" role="alert">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
    @endif

    Seccion para crear servicios

    <form action="{{ route('service.store') }}" class="form-horinzontal" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
        @include('services.form')
        <input type="submit" class="btn btn-primary" value="Agregar">
        <a class="btn btn-outline-secondary" href="{{route('service.index')}}">Regresar</a>
    </form>
</div>
@endsection

resources/views/services/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @if(count($errors)>0)
    <div class="alert alert-danger" role="alert">
        <ul>
            @foreach($errors->all() as $error)
            <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <h3>Seccion para editar servicio</h3>

    <form action="{{ route('service.update', $service) }}" class="form-horinzontal" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{method_field('PATCH')}}
        @include('services.form')
        <input type="submit" class="btn btn-primary" value="Modificar">
        <a class="btn btn-outline-secondary" href="{{route('service.index')}}">Regresar</a>
    </form>
</div>
@endsection

resources/views/services/form.blade.php
<div class="form-group">
    <label for="title" class="control-label">{{'Título'}}</label>
    <input
        type="text"
        class="form-control {{$errors->has('title')?'is-invalid':''}}"
        name="title"
        id="title"
        value="{{isset($service->title)?$service->title:old('title')}}">
        {!! $errors->first('title','<div class="alert alert-danger alert-dismissible">:message</div>')!!}
</div>

<!-- Categoría --> 
<div class="form-group">
  <label for="type_service_id">Seleccionar categoría: </label>
  <select class="form-control" name="type_service_id" id="type_service_id">
    @foreach($type_services as $type_service)
    <option value="{{$type_service->id}}">{{$type_service->category}}</option>
    @endforeach
  </select>
</div>

<!-- Description -->
<div class="form-group">
    <label for="description" class="control-label">{{'Descripción'}}</label>
    <textarea
        class="form-control"
        name="description"
        id="description"
        rows="3">{{ isset($service->description)?$service->description:old('description') }}</textarea>
</div>


<!-- Price -->
<div class="form-group">
    <label for="price" class="control-label">{{'Precio'}}</label>
    <input
        type="double"
        class="form-control {{$errors->has('price')?'is-invalid':''}}"
        name="price"
        id="price"
        value="{{isset($service->price)?$service->price:old('price')}}">
        {!! $errors->first('price','<div class="invalid-feedback">:message</div>')!!}
</div>


<!-- Picture -->
<div class="form-group justify-content-around">
    <label for="picture_path" class="control-label">{{'Imagen'}}</label>
    <div class="input-group">
        <div class="custom-file">
            <input
                type="file"
                class="custom-file-input"
                name="picture_path"
                id="picture_path">
        </div>
        <label class="custom-file-label" for="picture_path"></label>
    </div>
</div>

resources/views/services/getall.blade.php
@extends('adminlte::page')

@section('title', 'Servicios')

@section('content_header')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Services</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin">Admin</a></li>
                        <li class="breadcrumb-item active">Services</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@stop


@section('content')
    <div class="col-sm-13">

        <table class="table table-bordered table-striped dataTable table-hover text-center" id="example">

            <thead class="thead-light">
            <tr>
                <th>#</th>
                <th>id</th>
                <th>title</th>
                <th>operario</th>
                <th>categoría</th>
                <th>precio</th>
                <th>contratos</th>
            </tr>

            </thead>

            <tbody>
            @foreach($services as $service)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$service->id}}</td>
                    <td>{{$service->title}}</td>
                    <td>{{$service->user->profile->firstname . ' ' . $service->user->profile->lastname}}</td>
                    <td>{{$service->type_service->category}}</td>
                    <td>{{$service->price}}</td>
                    <td>{{$service->purchases->count()}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        @stop

        @section('js')
            <script>
                $(document).ready( function () {
                    $('#example').DataTable();
                } );
            </script>
@stop

resources/views/services/index.blade.php
@extends('adminlte::page')

@section('title', 'Servicios')

@section('content_header')

    <div class="col-sm-13">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item">
                <a href="{{ route('home') }}">Home</a>
            </li>
            <li class="breadcrumb-item active">
                Agregar Servicios
            </li>
        </ol>
    </div>


    <h1 class="m-0 text-dark">Administrar</h1>
    @if($busqueda)
        <h5 class="m-0 text-dark">Buscando: "{{$busqueda}}"</h5>
    @endif

@stop

@section('content')



    <div class="container">
        @if(Session::has('message'))
            <div class="alert alert-success" role="alert">
                {{Session::get('message')}}
            </div>
        @endif
    </div>


    <div class="col-sm-13">
        <ol class="btn btn-success float-sm-left">
            <a href="{{ route('service.create') }}" class="btn btn-success -item">Agregar Servicio <i class="fas fa-plus"></i></a>
        </ol>
    </div>
    <br/>
    <br/>

    <table class="table table-bordered table-striped dataTable table-hover text-center" id="example">

        <thead class="thead-light">
        <tr>
            <th><i class="fas fa-clipboard-check"></i></th>
            <th>Foto  <i class="fas fa-camera"></i></th>
            <th>Titulo  <i class="fas fa-tools"></i></th>
            <th>Categoría  <i class="fas fa-book-open"></i></th>
            <th>Precio(soles)  <i class="fas fa-hand-holding-usd"></i></th>
            <th>Descripción  <i class="fas fa-id-card"></i></th>
            <th>Acciones  <i class="fas fa-mouse"></i></th>
        </tr>

        </thead>

        <tbody>
        @foreach($services as $service)
            <tr>


                <td>{{$loop->iteration}}</td>

                <td>
                    <img src="{{asset('storage').'/'.$service->picture_path}}" class="img-thumbnail img-fluid" alt="" width="200">

                </td>
                <td>{{$service->title}}</td>
                @foreach($type_services as $type_service)
                    @if($service->type_service_id == $type_service->id)
                        <td>{{$type_service->category}}</td>
                    @endif
                @endforeach
                <td>{{$service->price}}</td>
                <td>{{$service->description}}</td>
                <td>

                    <a class="btn btn-warning" href="{{ route('service.edit', $service) }}">Editar
                    </a>
                    <a class="btn btn-info" href="{{ route('service.show', $service) }}">Ver
                    </a>
                    <form method="post" action="{{ route('service.destroy', $service) }}" style="display:inline">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}
                        <button class="btn btn-danger" type="submit" onclick="return confirm('¿Borrar?');">Borrar</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>

    </table>
@stop

@section('js')
    <script>
        $(document).ready( function () {
            $('#example').DataTable();
        } );
    </script>
@stop